// <auto-generated />
using System;
using HairdressingStudio.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HairdressingStudio.Migrations
{
    [DbContext(typeof(HairdressingStudioContext))]
    [Migration("20210525003059_HairdressingStudioMigration")]
    partial class HairdressingStudioMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HairdressingServicesStylists", b =>
                {
                    b.Property<int>("HairdressingServicesId")
                        .HasColumnType("int");

                    b.Property<int>("StylistsId")
                        .HasColumnType("int");

                    b.HasKey("HairdressingServicesId", "StylistsId");

                    b.HasIndex("StylistsId");

                    b.ToTable("HairdressingServicesStylists");
                });

            modelBuilder.Entity("HairdressingStudio.Models.Clients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PhoneNumber")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clients", "Studio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "poczekaj@o2.pl",
                            FirstName = "Edyta",
                            LastName = "Poczekaj",
                            PhoneNumber = 500500500
                        },
                        new
                        {
                            Id = 2,
                            Email = "bezdomny@o2.pl",
                            FirstName = "Jan",
                            LastName = "Bezdomny",
                            PhoneNumber = 606606606
                        });
                });

            modelBuilder.Entity("HairdressingStudio.Models.HairdressingServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCombining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceTime")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("HairdressingServices", "Studio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Strzyżenie przy pomocy nożyczek i maszynki",
                            IsActive = true,
                            IsCombining = false,
                            Name = "Strzyżenie włosów męskie - krótkie",
                            Price = 60m,
                            ServiceTime = 0.5m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mycie, masaż głowy, strzyżenie oraz modelowanie",
                            IsActive = true,
                            IsCombining = false,
                            Name = "Strzyżenie włosów i brody męskie - krótkie",
                            Price = 60m,
                            ServiceTime = 1m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Farbowanie przy użyciu najwyższej klasy produktów",
                            IsActive = true,
                            IsCombining = false,
                            Name = "Farbowanie - średnie",
                            Price = 60m,
                            ServiceTime = 1m
                        });
                });

            modelBuilder.Entity("HairdressingStudio.Models.Stylists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Stylists", "Studio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Magda",
                            IsActive = false
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Karina",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("HairdressingStudio.Models.StylistsWorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StylistsWorkingHours", "Studio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2021, 5, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2021, 5, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2021, 5, 4, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2021, 5, 4, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateTime(2021, 5, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 6,
                            EndDate = new DateTime(2021, 5, 5, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 7,
                            EndDate = new DateTime(2021, 5, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 8,
                            EndDate = new DateTime(2021, 5, 6, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 9,
                            EndDate = new DateTime(2021, 5, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 10,
                            EndDate = new DateTime(2021, 5, 7, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 11,
                            EndDate = new DateTime(2021, 5, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 12,
                            EndDate = new DateTime(2021, 5, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 13,
                            EndDate = new DateTime(2021, 5, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 14,
                            EndDate = new DateTime(2021, 5, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 15,
                            EndDate = new DateTime(2021, 5, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 16,
                            EndDate = new DateTime(2021, 5, 12, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 17,
                            EndDate = new DateTime(2021, 5, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 18,
                            EndDate = new DateTime(2021, 5, 13, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 19,
                            EndDate = new DateTime(2021, 5, 14, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 20,
                            EndDate = new DateTime(2021, 5, 14, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 14, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 21,
                            EndDate = new DateTime(2021, 5, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 22,
                            EndDate = new DateTime(2021, 5, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 23,
                            EndDate = new DateTime(2021, 5, 18, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 24,
                            EndDate = new DateTime(2021, 5, 18, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 18, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 25,
                            EndDate = new DateTime(2021, 5, 19, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 19, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 26,
                            EndDate = new DateTime(2021, 5, 19, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 19, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 27,
                            EndDate = new DateTime(2021, 5, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 28,
                            EndDate = new DateTime(2021, 5, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 29,
                            EndDate = new DateTime(2021, 5, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 21, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 30,
                            EndDate = new DateTime(2021, 5, 21, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 31,
                            EndDate = new DateTime(2021, 5, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 22, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 32,
                            EndDate = new DateTime(2021, 5, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 22, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 33,
                            EndDate = new DateTime(2021, 5, 25, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 34,
                            EndDate = new DateTime(2021, 5, 25, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 35,
                            EndDate = new DateTime(2021, 5, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 36,
                            EndDate = new DateTime(2021, 5, 26, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 37,
                            EndDate = new DateTime(2021, 5, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 38,
                            EndDate = new DateTime(2021, 5, 27, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 27, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 39,
                            EndDate = new DateTime(2021, 5, 28, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 40,
                            EndDate = new DateTime(2021, 5, 28, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 41,
                            EndDate = new DateTime(2021, 5, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 29, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 42,
                            EndDate = new DateTime(2021, 5, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 29, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 43,
                            EndDate = new DateTime(2021, 6, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 44,
                            EndDate = new DateTime(2021, 6, 1, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 45,
                            EndDate = new DateTime(2021, 6, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 46,
                            EndDate = new DateTime(2021, 6, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 47,
                            EndDate = new DateTime(2021, 6, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 48,
                            EndDate = new DateTime(2021, 6, 3, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 49,
                            EndDate = new DateTime(2021, 6, 4, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 50,
                            EndDate = new DateTime(2021, 6, 4, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 51,
                            EndDate = new DateTime(2021, 6, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 52,
                            EndDate = new DateTime(2021, 6, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 53,
                            EndDate = new DateTime(2021, 6, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 54,
                            EndDate = new DateTime(2021, 6, 8, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 8, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 55,
                            EndDate = new DateTime(2021, 6, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 56,
                            EndDate = new DateTime(2021, 6, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 9, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 57,
                            EndDate = new DateTime(2021, 6, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 58,
                            EndDate = new DateTime(2021, 6, 10, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 59,
                            EndDate = new DateTime(2021, 6, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 60,
                            EndDate = new DateTime(2021, 6, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 61,
                            EndDate = new DateTime(2021, 6, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 62,
                            EndDate = new DateTime(2021, 6, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 63,
                            EndDate = new DateTime(2021, 6, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 64,
                            EndDate = new DateTime(2021, 6, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 65,
                            EndDate = new DateTime(2021, 6, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 66,
                            EndDate = new DateTime(2021, 6, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 67,
                            EndDate = new DateTime(2021, 6, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 68,
                            EndDate = new DateTime(2021, 6, 17, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 69,
                            EndDate = new DateTime(2021, 6, 18, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 70,
                            EndDate = new DateTime(2021, 6, 18, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 18, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 71,
                            EndDate = new DateTime(2021, 6, 19, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 19, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 72,
                            EndDate = new DateTime(2021, 6, 19, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 19, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 73,
                            EndDate = new DateTime(2021, 6, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 74,
                            EndDate = new DateTime(2021, 6, 22, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 75,
                            EndDate = new DateTime(2021, 6, 23, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 23, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 76,
                            EndDate = new DateTime(2021, 6, 23, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 23, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 77,
                            EndDate = new DateTime(2021, 6, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 78,
                            EndDate = new DateTime(2021, 6, 24, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 24, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 79,
                            EndDate = new DateTime(2021, 6, 25, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 80,
                            EndDate = new DateTime(2021, 6, 25, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 81,
                            EndDate = new DateTime(2021, 6, 26, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 82,
                            EndDate = new DateTime(2021, 6, 26, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 83,
                            EndDate = new DateTime(2021, 6, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 84,
                            EndDate = new DateTime(2021, 6, 29, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 29, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 85,
                            EndDate = new DateTime(2021, 6, 30, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 86,
                            EndDate = new DateTime(2021, 6, 30, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 30, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 87,
                            EndDate = new DateTime(2021, 7, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 88,
                            EndDate = new DateTime(2021, 7, 1, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 89,
                            EndDate = new DateTime(2021, 7, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 90,
                            EndDate = new DateTime(2021, 7, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 91,
                            EndDate = new DateTime(2021, 7, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 92,
                            EndDate = new DateTime(2021, 7, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 93,
                            EndDate = new DateTime(2021, 7, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 94,
                            EndDate = new DateTime(2021, 7, 6, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 95,
                            EndDate = new DateTime(2021, 7, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 96,
                            EndDate = new DateTime(2021, 7, 7, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 97,
                            EndDate = new DateTime(2021, 7, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 98,
                            EndDate = new DateTime(2021, 7, 8, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 8, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 99,
                            EndDate = new DateTime(2021, 7, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 100,
                            EndDate = new DateTime(2021, 7, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 9, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 101,
                            EndDate = new DateTime(2021, 7, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 102,
                            EndDate = new DateTime(2021, 7, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 103,
                            EndDate = new DateTime(2021, 7, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 104,
                            EndDate = new DateTime(2021, 7, 13, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 105,
                            EndDate = new DateTime(2021, 7, 14, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 106,
                            EndDate = new DateTime(2021, 7, 14, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 14, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 107,
                            EndDate = new DateTime(2021, 7, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 108,
                            EndDate = new DateTime(2021, 7, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 109,
                            EndDate = new DateTime(2021, 7, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 110,
                            EndDate = new DateTime(2021, 7, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 111,
                            EndDate = new DateTime(2021, 7, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 112,
                            EndDate = new DateTime(2021, 7, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 113,
                            EndDate = new DateTime(2021, 7, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 114,
                            EndDate = new DateTime(2021, 7, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 115,
                            EndDate = new DateTime(2021, 7, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 21, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 116,
                            EndDate = new DateTime(2021, 7, 21, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 117,
                            EndDate = new DateTime(2021, 7, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 118,
                            EndDate = new DateTime(2021, 7, 22, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 119,
                            EndDate = new DateTime(2021, 7, 23, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 23, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 120,
                            EndDate = new DateTime(2021, 7, 23, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 23, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 121,
                            EndDate = new DateTime(2021, 7, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 122,
                            EndDate = new DateTime(2021, 7, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 123,
                            EndDate = new DateTime(2021, 7, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 124,
                            EndDate = new DateTime(2021, 7, 27, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 27, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 125,
                            EndDate = new DateTime(2021, 7, 28, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 126,
                            EndDate = new DateTime(2021, 7, 28, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 127,
                            EndDate = new DateTime(2021, 7, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 128,
                            EndDate = new DateTime(2021, 7, 29, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 29, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 129,
                            EndDate = new DateTime(2021, 7, 30, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 130,
                            EndDate = new DateTime(2021, 7, 30, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 30, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 131,
                            EndDate = new DateTime(2021, 7, 31, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 132,
                            EndDate = new DateTime(2021, 7, 31, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 133,
                            EndDate = new DateTime(2021, 8, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 134,
                            EndDate = new DateTime(2021, 8, 3, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 135,
                            EndDate = new DateTime(2021, 8, 4, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 136,
                            EndDate = new DateTime(2021, 8, 4, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 137,
                            EndDate = new DateTime(2021, 8, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 138,
                            EndDate = new DateTime(2021, 8, 5, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 139,
                            EndDate = new DateTime(2021, 8, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 140,
                            EndDate = new DateTime(2021, 8, 6, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 141,
                            EndDate = new DateTime(2021, 8, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 7, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 142,
                            EndDate = new DateTime(2021, 8, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 7, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 143,
                            EndDate = new DateTime(2021, 8, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 144,
                            EndDate = new DateTime(2021, 8, 10, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 145,
                            EndDate = new DateTime(2021, 8, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 146,
                            EndDate = new DateTime(2021, 8, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 147,
                            EndDate = new DateTime(2021, 8, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 148,
                            EndDate = new DateTime(2021, 8, 12, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 149,
                            EndDate = new DateTime(2021, 8, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 150,
                            EndDate = new DateTime(2021, 8, 13, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 151,
                            EndDate = new DateTime(2021, 8, 14, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 14, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 152,
                            EndDate = new DateTime(2021, 8, 14, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 14, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 153,
                            EndDate = new DateTime(2021, 8, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 154,
                            EndDate = new DateTime(2021, 8, 17, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 155,
                            EndDate = new DateTime(2021, 8, 18, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 156,
                            EndDate = new DateTime(2021, 8, 18, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 18, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 157,
                            EndDate = new DateTime(2021, 8, 19, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 158,
                            EndDate = new DateTime(2021, 8, 19, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 19, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 159,
                            EndDate = new DateTime(2021, 8, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 160,
                            EndDate = new DateTime(2021, 8, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 161,
                            EndDate = new DateTime(2021, 8, 21, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 21, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 162,
                            EndDate = new DateTime(2021, 8, 21, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 21, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 163,
                            EndDate = new DateTime(2021, 8, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 164,
                            EndDate = new DateTime(2021, 8, 24, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 8, 24, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        });
                });

            modelBuilder.Entity("HairdressingStudio.Models.Visits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCanceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ServiceComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StylistId");

                    b.ToTable("Visits", "Studio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 2,
                            IsCanceled = false,
                            ServiceDate = new DateTime(2021, 4, 6, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 2,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            IsCanceled = false,
                            ServiceDate = new DateTime(2021, 4, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 3,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 2,
                            IsCanceled = false,
                            ServiceDate = new DateTime(2021, 4, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 1,
                            StylistId = 1
                        });
                });

            modelBuilder.Entity("HairdressingServicesStylists", b =>
                {
                    b.HasOne("HairdressingStudio.Models.HairdressingServices", null)
                        .WithMany()
                        .HasForeignKey("HairdressingServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairdressingStudio.Models.Stylists", null)
                        .WithMany()
                        .HasForeignKey("StylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HairdressingStudio.Models.Visits", b =>
                {
                    b.HasOne("HairdressingStudio.Models.Clients", "Clients")
                        .WithMany("Visits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairdressingStudio.Models.HairdressingServices", "HairdressingServices")
                        .WithMany("Visits")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairdressingStudio.Models.Stylists", "Stylists")
                        .WithMany("Visits")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clients");

                    b.Navigation("HairdressingServices");

                    b.Navigation("Stylists");
                });

            modelBuilder.Entity("HairdressingStudio.Models.Clients", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("HairdressingStudio.Models.HairdressingServices", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("HairdressingStudio.Models.Stylists", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
