// <auto-generated />
using System;
using HairdressingStudio.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HairdressingStudio.Migrations
{
    [DbContext(typeof(HairdressingStudioContext))]
    [Migration("20210402235514_HairdressingStudio")]
    partial class HairdressingStudio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HairdressingServicesStylists", b =>
                {
                    b.Property<int>("HairdressingServicesId")
                        .HasColumnType("int");

                    b.Property<int>("StylistsId")
                        .HasColumnType("int");

                    b.HasKey("HairdressingServicesId", "StylistsId");

                    b.HasIndex("StylistsId");

                    b.ToTable("HairdressingServicesStylists");
                });

            modelBuilder.Entity("HairdressingStudio.Models.Clients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PhoneNumber")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clients", "Studio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "poczekaj@o2.pl",
                            FirstName = "Edyta",
                            LastName = "Poczekaj",
                            PhoneNumber = 500500500
                        },
                        new
                        {
                            Id = 2,
                            Email = "bezdomny@o2.pl",
                            FirstName = "Jan",
                            LastName = "Bezdomny",
                            PhoneNumber = 606606606
                        });
                });

            modelBuilder.Entity("HairdressingStudio.Models.HairdressingServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCombining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceTime")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("HairdressingServices", "Studio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Strzyżenie przy pomocy nożyczek i maszynki",
                            IsActive = true,
                            IsCombining = false,
                            Name = "Strzyżenie włosów męskie - krótkie",
                            Price = 60m,
                            ServiceTime = 0.5m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mycie, masaż głowy, strzyżenie oraz modelowanie",
                            IsActive = true,
                            IsCombining = false,
                            Name = "Strzyżenie włosów i brody męskie - krótkie",
                            Price = 60m,
                            ServiceTime = 1m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Farbowanie przy użyciu najwyższej klasy produktów",
                            IsActive = true,
                            IsCombining = false,
                            Name = "Farbowanie - średnie",
                            Price = 60m,
                            ServiceTime = 1m
                        });
                });

            modelBuilder.Entity("HairdressingStudio.Models.Stylists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Stylists", "Studio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Magda"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Karina"
                        });
                });

            modelBuilder.Entity("HairdressingStudio.Models.StylistsWorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StylistsWorkingHours", "Studio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2021, 4, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2021, 4, 1, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2021, 4, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2021, 4, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateTime(2021, 4, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 6,
                            EndDate = new DateTime(2021, 4, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 7,
                            EndDate = new DateTime(2021, 4, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 8,
                            EndDate = new DateTime(2021, 4, 6, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 9,
                            EndDate = new DateTime(2021, 4, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 10,
                            EndDate = new DateTime(2021, 4, 7, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 11,
                            EndDate = new DateTime(2021, 4, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 12,
                            EndDate = new DateTime(2021, 4, 8, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 8, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 13,
                            EndDate = new DateTime(2021, 4, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 14,
                            EndDate = new DateTime(2021, 4, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 9, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 15,
                            EndDate = new DateTime(2021, 4, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 16,
                            EndDate = new DateTime(2021, 4, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 17,
                            EndDate = new DateTime(2021, 4, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 18,
                            EndDate = new DateTime(2021, 4, 13, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 19,
                            EndDate = new DateTime(2021, 4, 14, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 20,
                            EndDate = new DateTime(2021, 4, 14, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 14, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 21,
                            EndDate = new DateTime(2021, 4, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 22,
                            EndDate = new DateTime(2021, 4, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 23,
                            EndDate = new DateTime(2021, 4, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 24,
                            EndDate = new DateTime(2021, 4, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 25,
                            EndDate = new DateTime(2021, 4, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 26,
                            EndDate = new DateTime(2021, 4, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 27,
                            EndDate = new DateTime(2021, 4, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 28,
                            EndDate = new DateTime(2021, 4, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 29,
                            EndDate = new DateTime(2021, 4, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 21, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 30,
                            EndDate = new DateTime(2021, 4, 21, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 31,
                            EndDate = new DateTime(2021, 4, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 32,
                            EndDate = new DateTime(2021, 4, 22, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 33,
                            EndDate = new DateTime(2021, 4, 23, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 23, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 34,
                            EndDate = new DateTime(2021, 4, 23, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 23, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 35,
                            EndDate = new DateTime(2021, 4, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 36,
                            EndDate = new DateTime(2021, 4, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 37,
                            EndDate = new DateTime(2021, 4, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 38,
                            EndDate = new DateTime(2021, 4, 27, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 27, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 39,
                            EndDate = new DateTime(2021, 4, 28, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 40,
                            EndDate = new DateTime(2021, 4, 28, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 41,
                            EndDate = new DateTime(2021, 4, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 42,
                            EndDate = new DateTime(2021, 4, 29, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 29, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 43,
                            EndDate = new DateTime(2021, 4, 30, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 44,
                            EndDate = new DateTime(2021, 4, 30, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 30, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 45,
                            EndDate = new DateTime(2021, 5, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 46,
                            EndDate = new DateTime(2021, 5, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 47,
                            EndDate = new DateTime(2021, 5, 4, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 48,
                            EndDate = new DateTime(2021, 5, 4, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 49,
                            EndDate = new DateTime(2021, 5, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 50,
                            EndDate = new DateTime(2021, 5, 5, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 51,
                            EndDate = new DateTime(2021, 5, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 52,
                            EndDate = new DateTime(2021, 5, 6, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 53,
                            EndDate = new DateTime(2021, 5, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 54,
                            EndDate = new DateTime(2021, 5, 7, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 55,
                            EndDate = new DateTime(2021, 5, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 56,
                            EndDate = new DateTime(2021, 5, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 5, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1
                        });
                });

            modelBuilder.Entity("HairdressingStudio.Models.Visits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StylistId");

                    b.ToTable("Visits", "Studio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            ServiceDate = new DateTime(2021, 4, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 2,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            ServiceDate = new DateTime(2021, 4, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 3,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 1,
                            ServiceDate = new DateTime(2021, 4, 6, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 1,
                            StylistId = 1
                        });
                });

            modelBuilder.Entity("HairdressingServicesStylists", b =>
                {
                    b.HasOne("HairdressingStudio.Models.HairdressingServices", null)
                        .WithMany()
                        .HasForeignKey("HairdressingServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairdressingStudio.Models.Stylists", null)
                        .WithMany()
                        .HasForeignKey("StylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HairdressingStudio.Models.Visits", b =>
                {
                    b.HasOne("HairdressingStudio.Models.Clients", "Clients")
                        .WithMany("Visits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairdressingStudio.Models.HairdressingServices", "HairdressingServices")
                        .WithMany("Visits")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairdressingStudio.Models.Stylists", "Stylists")
                        .WithMany("Visits")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clients");

                    b.Navigation("HairdressingServices");

                    b.Navigation("Stylists");
                });

            modelBuilder.Entity("HairdressingStudio.Models.Clients", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("HairdressingStudio.Models.HairdressingServices", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("HairdressingStudio.Models.Stylists", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
